spring:
  profiles:
    active: local

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

server:
  port: 8092


  
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
